name: Try action

on:
  push:
    branches:
      - try-action

permissions: write-all

jobs:
  update_env_vars:
    runs-on: ubuntu-latest
    environment: try-action
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Environment Variables
        run: gh variable set TRY_ACTION --body "12345" -e try-action
