name: Build and push to ecr

on:
  push:
    branches: ["prod"]
  pull_request:
    branches: ["prod"]

permissions: write-all

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/${{ vars.PROJECT_NAME }} .
  version:
    name: Get current version
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    needs: build
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Get current tag
        id: get-current-tag
        run: |
          bash ./build/get_current_tag.sh
    outputs:
      CURRENT_TAG: ${{ steps.get-current-tag.outputs.CURRENT_VERSION }}

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    needs: version
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: tannvdev19/sample-nodejs

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ vars.PROJECT_NAME }}:${{ needs.version.outputs.NEW_TAG }}
          labels: ${{ steps.meta.outputs.labels }}

  push_to_ecr:
    name: Push docker image to ECR
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    needs: version
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ vars.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ needs.version.outputs.CURRENT_VERSION}}
        run: |
          echo "Image tag: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          docker build --tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
