name: Terraform-Github-Destroy

on:
  workflow_dispatch:
    inputs:
      destroyType:
        description: "Do you want to destroy (no or yes)?"
        required: true
        default: "no"

permissions:
  contents: read

jobs:
  tf-destroy:
    name: Terraform destroy
    runs-on: ubuntu-latest
    env:
      environment: $GITHUB_REF_NAME
    steps:
      - name: egeogjie
        run: echo "1244f"

