name: Create ECR

on:
  workflow_dispatch:
    inputs:
      choice-branch:
        type: choice
        description: "Choose the environment to deploy ecr"
        default: "dev"
        options:
          - "dev"
          - "prod"

permissions: write-all

jobs:
  create_ecr:
    name: Create AWS ECR with Terraform
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.choice-branch }}
    env:
      environment: ${{ github.event.inputs.choice-branch }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: infra
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Terraform init
        working-directory: ./env-${{env.environment}}
        run: terraform init
      - name: Terraform plan
        working-directory: ./env-${{env.environment}}
        run: terraform plan
      - name: Terraform apply
        working-directory: ./env-${{env.environment}}
        run: terraform apply -auto-approve
      - name: Terraform output
        id: tf-output
        working-directory: ./env-${{env.environment}}
        run: echo "ECR_REPO_URL=$(terraform output ecr_repo_url)" >> $GITHUB_OUTPUT
        
    outputs:
      ECR_REPO_URL: ${{ steps.tf-output.outputs.ECR_REPO_URL }}
  update_variables:
    name: Update Github Variables
    runs-on: ubuntu-latest
    needs: create_ecr
    environment: ${{ github.event.inputs.choice-branch }}
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      environment: ${{ github.event.inputs.choice-branch }}
      repo_url: ${{ needs.create_ecr.outputs.ECR_REPO_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: prod
      - name: Update Github Variables
        run: |
          echo "url: ${{ env.repo_url }}" 
          bash ./bash-script/update-vars.sh -e ${{env.environment}} -u ${{ env.repo_url }}
        # run: gh variable set ECR_REPO_URL -b ${{ needs.create_ecr.outputs.ecr_repo_url }} -e ${{env.environment}}}
