name: Create infrastruture

on:
  workflow_dispatch:
    inputs:
      choice-branch:
        type: choice
        description: "Choose the environment to deploy ecr"
        default: "dev"
        options:
          - "dev"
          - "prod"

permissions: write-all

jobs:
  create_ecr:
    name: Create AWS ECR with Terraform
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.choice-branch }}
    env:
      environment: ${{ github.event.inputs.choice-branch }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: infra
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
          mask-aws-account-id: "no"
      - name: Terraform init
        working-directory: ./env-${{env.environment}}
        run: terraform init
      - name: Terraform plan
        working-directory: ./env-${{env.environment}}
        run: terraform plan
      - name: Terraform apply
        working-directory: ./env-${{env.environment}}
        run: terraform apply -auto-approve
      - name: Terraform output
        id: tf-output
        working-directory: ./env-${{env.environment}}
        run: |
          echo "ECR_REPO_URL=$(terraform output ecr_repo_url)" >> $GITHUB_OUTPUT
          echo "SSH_PRIVATE_KEY=$(terraform output ssh_private_key)" >> $GITHUB_OUTPUT
          echo "EC2_PUBLIC_IP=$(terraform output ec2_public_ip)" >> $GITHUB_OUTPUT
    outputs:
      ECR_REPO_URL: ${{ steps.tf-output.outputs.ECR_REPO_URL }}
      SSH_PRIVATE_KEY: ${{ steps.tf-output.outputs.SSH_PRIVATE_KEY }}
      EC2_PUBLIC_IP: ${{ steps.tf-output.outputs.EC2_PUBLIC_IP }}

  update_variables:
    name: Update Github Variables
    runs-on: ubuntu-latest
    needs: create_ecr
    environment: ${{ github.event.inputs.choice-branch }}
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      ENVIRONMENT: ${{ github.event.inputs.choice-branch }}
      REPO_URL: ${{ needs.create_ecr.outputs.ECR_REPO_URL }}
      SSH_PRIVATE_KEY: ${{ needs.create_ecr.outputs.SSH_PRIVATE_KEY }}
      EC2_PUBLIC_IP: ${{ needs.create_ecr.outputs.EC2_PUBLIC_IP }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: prod
      - name: Update Github Variables
        run: |
          echo "url: ${{ env.repo_url }}" 
          bash ./bash-script/update-vars.sh -e ${{env.environment}} -u ${{ env.repo_url }}
          gh secret set SSH_PRIVATE_KEY -b ${{ env.SSH_PRIVATE_KEY }} -e ${{env.environment}}
          gh secret set EC2_PUBLIC_IP -b ${{ env.EC2_PUBLIC_IP }} -e ${{env.environment}}
        # run: gh variable set ECR_REPO_URL -b ${{ needs.create_ecr.outputs.ecr_repo_url }} -e ${{env.environment}}}
