name: Destroy terraform

on:
    workflow_dispatch:
        inputs:
            choice-branch:
                type: choice
                description: 'Choose the environment to destroy ecr'
                default: 'dev'
                options:
                    - 'dev'
                    - 'prod'

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
        environment: ${{ github.event.inputs.choice-branch }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            ref: infra
      - name: Config AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Terraform init
        working-directory: ./env-${{env.environment}}
        run: terraform init

      - name: Terraform destroy
        working-directory: ./env-${{env.environment}}
        run: terraform destroy -auto-approve