name: Create tag and push to ecr

on:
  # push:
  #   branches: ["prod"]
  # pull_request:
  #   branches: ["prod"]
  workflow_dispatch:
    inputs:
      confirm-create-tag:
        type: choice
        description: "Do you want to create tag and push (no or yes)?"
        default: "no"
        options: ["yes", "no"]
      update-version-type:
        description: "Do you want to create new tags for major, minor or patch?"
        type: choice
        options: ["patch", "minor", "major"]
        default: patch

permissions: write-all

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    environment: $GITHUB_REF_NAME
    if: github.event.inputs.confirm-create-tag == 'yes'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/${{ vars.PROJECT_NAME }} .

  create_version:
    name: Create tag base of previous tag
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          bash ./build/git_update_2.sh -v ${{github.event.inputs.update-version-type}}
    outputs:
      NEW_TAG: ${{ steps.increment-git-tag.outputs.NEW_TAG }}
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    environment: $GITHUB_REF_NAME
    needs: create_version
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: tannvdev19/sample-nodejs

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ vars.PROJECT_NAME }}:${{ needs.create_version.outputs.NEW_TAG }}
          labels: ${{ steps.meta.outputs.labels }}

  push_to_ecr:
    name: Push docker image to ECR
    runs-on: ubuntu-latest
    environment: $GITHUB_REF_NAME
    needs: create_version
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ vars.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ needs.create_version.outputs.NEW_TAG}}
        run: |
          echo "Image tag: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          docker build --tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
